version: "3.5"
  
services:
  frontend:
    build: ./frontend
    restart: always
    image: frontend
    container_name: frontend
    depends_on:
      -  app-sentiment
    ports:
      - 3000:80

  app-sentiment:
    build: ./webapp
    restart: always
    image: webapp
    container_name: webapp
    depends_on:
      - logic
    ports:
      - 8080:8080
    environment:
      - SA_LOGIC_API_URL=http://logic:5000
  logic:
    build: ./logic
    restart: always
    image:  logic
    container_name: logic
