version: "3"
  
services:
  frontend:
    build: ./frontend
    restart: always
    image: frontend
    container_name: frontend
    depends_on:
      -  app-sentiment
    ports:
      - 80:3000

  app-sentiment:
    build: ./webapp
    restart: always
    image: webapp
    container_name: webapp
    depends_on:
      - logic
    ports:
      - 5000
  logic:
 build: ./logic
    restart: always
    image:  logic
    container_name: logic
    ports:
      - "5000:8080"
    environment:
      - SA_LOGIC_API_URL=http://localhost:5000
